version: '3.7'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/backend
      - /frontend/node_modules
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules